language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://agonzalezc.pactflow.io
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "ZqvL90fyHsQ1vvFDS4AMVx4C9k7gPWI3NNSYemHwQ03Xlnr93bg3HsN7mHeQ7A9TJwsWLaRk4qff9NtAmFmNKVZvyjZLuXG4BqEFzl1LL29SRA2KKzrpel87vqGHGx3xosDzbCJNzeMV3dIs60x7kUJU3RN9ozTki6zMc3xDnI2GYKtkIKNFTIDiBBvpeeRbRB+bDwbu6KQeJmwRoM3+zEO3UCiBRl2Mu9GwfpZfaiM8r226c1S6mN40fbTsjwf/g6LBfvpoXv40jB4SxxAMNZgYojRkfTslYuuFWtQZsS/vlhrlsLf6BBNUo/+exg13P7paioLSFd2rCxRT2aOo76WSrvWAs411kWbovJOFhgaP+Duz4amKDphSRaUiWmsFEe5IoHadAPyt6EyESnNMnXVhHcAq+NJKncla+SM0HY/7R9XdXUoG2FcUoLOge6RWcrXR4pJmGx/pVMn1zJkdvGXM6KVmiDJ1rDRlzasG2i4wUQYpeQJVrjHjizWnic9q2M2z03srMgv2ftiPTLESifKP5ZfI7lAlqFWhA+ObCyuTXnR5xF3EiaIrnB6wjjD5Fk0ZhWYbVvuzisJ0E9OeNCVDN7sq01Kj4BQhjZarPFJrhk3bX01AM1oF1h5X751LMjSpBdXvLMzTbRT2VoLyNxA0DhPX6WPABIRoKIei/2s="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
